#!/bin/bash
#HEAD#########################################################
#
# Katana Framework | dependencies
# The below dependencies this installed in most pentest distros,
# but in other distro's as UBUNTU not is installed.
#
# aircrack-ng for wireless modules
# nmap for network scan modules and some functions
# apache2 for SET modules
# ettercap for MIMT modules
# dhcpd for rogues AP
#
# 
# Last Modified: 2/06/2016
# 0xicl33n:
# - trying to make more elegant, isnt working.

# Last Modified: 03/06/2016
#
#########################################################HEAD#


#sudo apt-get update
#sudo apt-get upgrade
DEPS=''
if [grep -xq "Kali" /etc/issue]
	then
		if ! hash aircrack-ng 2>/dev/null; then 
			DEPS+="aircrack-ng "
		fi

		if ! hash nmap 2>/dev/null; then 
			DEPS+="nmap "
		fi
		
		if ! hash apache2 2>/dev/null; then 
			DEPS+="apache2 php5 libapache2-mod-php5 "
		fi


		if ! hash ettercap 2>/dev/null; then 
			DEPS+="ettercap-text-only " 
		fi

		if ! hash dhcpd 2>/dev/null; then 
			DEPS+="isc-dhcp-server "
		fi
		echo $DEPS
else:
	echo "We aint on kali"
DIR=$(dirname $0)
cd $DIR
git submodule update --init --recursive
cd $DIR/lib/scapy/
sudo python setup.py install
cd $DIR/py/paimei/
sudo python setup.py install
cd $DIR/py/pydbg/
sud python setup.py install
