#!/usr/bin/env python
#HEAD#########################################################
#
# Katana Framework | dependencies
# The below dependencies this installed in most pentest distros,
# but in other distro's as UBUNTU not is installed.
#
# aircrack-ng for wireless modules
# nmap for network scan modules and some functions
# apache2 for SET modules
# ettercap for MIMT modules
# dhcpd for rogues AP
#
# 
# Last Modified: 2/06/2016
#
# 0xicl33n notes:
# - made more intelligent, looks for debian or kali before running apt
# - added macchanger to list of dependancies (beta)
#
#########################################################HEAD#


if cat /etc/issue | grep -Fxq "Kali" | grep -Fxq "Debian"
then
	sudo apt-get update
	if ! hash aircrack-ng 2>/dev/null; then 
		sudo apt-get install --yes aircrack-ng
	fi

	if ! hash nmap 2>/dev/null; then 
		sudo apt-get install --yes nmap
	fi

	if ! hash apache2 2>/dev/null; then 
		sudo apt-get install --yes apache2
		sudo apt-get install --yes php5
		sudo apt-get install --yes libapache2-mod-php5
	fi

	if ! hash ettercap 2>/dev/null; then 
		sudo apt-get install ettercap-text-only
	fi

	if ! hash dhcpd 2>/dev/null; then 
		sudo apt-get install isc-dhcp-server
	fi

	if ! hash macchanger 2>/dev/null; then 
		sudo apt-get install macchanger
	fi
fi


DIR=$(dirname $0)
cd $DIR/lib/scapy/
sudo python setup.py install
