#!/bin/bash
#HEAD#########################################################
#
# Katana Framework | dependencies
# The below dependencies this installed in most pentest distros,
# but in other distro's as UBUNTU not is installed.
#
# aircrack-ng for wireless modules
# nmap for network scan modules and some functions
# apache2 for SET modules
# ettercap for MIMT modules
# dhcpd for rogues AP
#
# 
# Last Modified: 2/06/2016
#
# 0xicl33n:
# - Simplified process. Added submodules
# Last Modified: 03/06/2016
#
#########################################################HEAD#



DEPS=''

if ! hash aircrack-ng 2>/dev/null; then 
	DEPS+="aircrack-ng "
fi

if ! hash nmap 2>/dev/null; then 
	DEPS+="nmap "
fi

if ! hash apache2 2>/dev/null; then 
	DEPS+="apache2 php5 libapache2-mod-php5 "
fi


if ! hash ettercap 2>/dev/null; then 
	DEPS+="ettercap-text-only " 
fi

if ! hash dhcpd 2>/dev/null; then 
	DEPS+="isc-dhcp-server "
fi
sudo apt-get update
sudo apt-get install -y $DEPS wget unzip python-pip python-mysqldb
DIR=$(dirname $0)
cd $DIR
git submodule update --init --recursive
#whois
pip install python-whois
#cd $DIR/tmp
#rarfile
#wget https://github.com/markokr/rarfile/archive/rarfile_2_7.zip
pip install rarfile==2.7
#scapy
pip install scapy==2.3.1
#wget https://github.com/secdev/scapy/archive/v2.3.1.zip
#unzip -o v2.3.1.zip -d $DIR/tmp/
#cp -r $DIR/tmp/scapy-2.3.1/ $DIR/lib/scapy
#cd $DIR/lib/scapy/
#sudo python setup.py install
#
cd $DIR/lib/paimei/
sudo python setup.py install
cd $DIR/lib/paimei/pydbg/
sudo python setup.py install